### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by amnesiaonline** [themarcba/twitter-username-bot#1]
completely new to npm as well as anything cmd line in general, so sorry if this is a very ignorant question, but i keep getting this error:

```
[nodemon] starting `node src/index.js`
D:\Downloads\twitter-username-bot-master\twitter-username-bot-master\src\index.js:11
process.env.DESIRED_USERNAMES.split(',').map(u => u.trim()).forEach(username => {
                              ^

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (D:\Downloads\twitter-username-bot-master\twitter-username-bot-master\src\index.js:11:31)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by themarcba** [comment]
It looks like you didn't define a .env file.
Create a file named `.env` in your project root folder, and add the following content:

```bash
DESIRED_USERNAMES='batman, superman, flash, wonderwoman'
SENDGRID_API_KEY=mysupersecreatapikeygiventomebysendgrid
EMAIL_FROM=bot@example.com
EMAIL_TO=youremail@example.com

```
DESIRED_USERNAMES being a comma-separated list of usernames you want to watch out for and SENDGRID_API_KEY the API key from SendGrid (you have to create an account there for this to work).
